### ISSUE TITLE
Bug when running on JRE 8u45

### ISSUE THREAD

**Issue by nmarshall23** [SvenKayser/JMOD#38] opened 2016-11-15 17:08 UTC
After merging with the master branch I get a JMODLoader warning, Failed to parse JSON from. 

I've debuged it to a Nashorn exception: `TypeError: Cannot call undefined in <eval>`, in `LoaderUtil.parseModJson(rawjson);`

After a lot of googling, this looks like a bug in JRE 8u45. 
From http://www.oracle.com/technetwork/java/javase/8u45-relnotes-2494160.html
> Nashorn has known issues where it incorrectly compiles try/finally constructs. 

The release notes for JRE 8u60 say that bug was fixed. 

I can confirm that do not have any issues on JRE 8u111. My desktop and laptop have no issues, it's my hosted server that so far is resisting updating their JRE. They are running JRE 8u45. 

Take a look at the published [workarounds](https://wiki.openjdk.java.net/pages/viewpage.action?pageId=22937606). 

I think we should try and use the workarounds as most people don't look at the minor version numbers.

**Comment by SvenKayser** [comment] 2017-03-02 00:20
The fix for this poses other problems. Iirc you cannot use comments with Gson, which is the original reason I dropped it for parsing the json files.

**Comment by SvenKayser** [comment] 2017-03-10 13:24
I guess I'll implement manual removal of comments and switch (back) to GSON after that. The problem is that https://github.com/google/gson/issues/212 wasn't fixed in GSON 2.2.4 yet.

**Comment by SvenKayser** [comment] 2017-03-11 13:23
Resolved as of https://github.com/SvenKayser/JMOD/commit/1aa09504fba61e83598793371c5e720fbca29baf

**Closed as completed by SvenKayser** 2017-03-11 13:23 UTC
Labels: Open for discussion
